dist: xenial
sudo: required
language: python
python:
  - '3.5'
  - '3.6'
  - '3.7'
services:
- docker
env:
  global:
  - REPO=crops/toolchain
  - secure: lyIJFBXkaIC3o1XqEVctU16ETgqRvY6vAwxqI7qag6/bb+ybS+oTQaO+kIbkh/Ky0f9IOkmsZXbZSD3bylTjY2PFQjt3CZeRd1xVgvtlCs2AfGqaNP+DaeWYD3HaVreauFBJKQKPfWCvfs3bwQLQw3UdC+h1cYfuXODISyLQsjjyPmNpWCEbYt7zu47P7qqXCMOo6HARV3w25gOGyP+w2nk2uE8L82NRVa+ALD535Vv+UPiyNyHS+7QmLIyNXkUqqyyOUJd5eZglQhhWNicgPWE0rWF1w0Bgw91uhlrClBD5IawJ1Wt33Ll8fJl+/cqgVVltRMqN/NUzndIJfXxsBwK1s/kJoGT4Eh0khQeO3WtQ4KOQZkeus9TnmGm1I1JSomf/WOge7EG9g3tPGHFcyUeNgi5WiPAp2oEGyqwGv8bJsqdPALRlyl2q7kPP5RZko/QOKWEZCsw3L3JmCJcsdGzmF7mZn3ZLx7N/xE7TSr11MyWWuJ4GUhO/GbaUqxNdCDVKxCH7iAmtzB+lRibJcmt5kI/ewOoP5iBR3onYIyebcKOjUQgxwYY2S9MwndbzreCExX+Z1GGCiSwfewOypLMfRkVwZ00hIkDvq9fmF2iADsL2KH61JKL84RZPeoEhhnyr3DhTd+Y9k4tsik9L17NG1cah6HIVPCp1rlX0O2k=
  - secure: F4Wq8ZKhClZaNNDBbuPJ6L+M6HySby0Tm/6ziyXsvNJDcB66LSVErya5XuQhKt7kR5UIiI2CkQL63sQ0B5Q3P56cZ4zSsddBJ13bHtaK4FL6rA2sln0R7dWu18hWOjSpRTvwiTNTzvS97SAPpDTpDMeTW/NvZSFPY0GqgrLsl7YPNJ7lXEOSVhhRJuiD6SRsMFsnDjk5vOHZe5Yqb0I+U2RcbxF8C6T/q/oYzCbJ7dsjX4JZTxcvkglNrDctM+e5G7r5YWjs7X9jNLEJEgoBVJifA9+9tZC4W/mTxfIFIlRqz8Aq+50R86AU1jpxE4ruVaTHiL5KdpG/YtWsKsdVVfTN1j1wWpLebUgLgGZNOVre1X4CMjnc79N+4yfCb2NhRo/Bp5ytYxcgwyyFKSbquVuPJP3OUwtIRUfjhF+ju3gTRg5YP2jc91Ho6AKf3jnOGTvk9t5P4zMvRsRN6KWHAnAl/IYxD5uLaw9fgxpCzWbPR7kSPTT4zA3R7p0udH60epPSj0phaJeoKZw6KwFUpKyojoPLeKUCH1iF7o0gaD7+geX2hfuexzRmMJXCsyK/smzCmtm4pLdjv1R+QAKzFg88vu21hQtqHKTMJgO11+9HfX/BH0NGAM0GPK42U3cZxpwRZ1C3ur2lCmexDpUyFQbNxQWJjcFRDtTv1xllTJk=
  - secure: fX+gKqLIvJLE2MkltrDT4ZV6u2mkWn5hFD0LXcU7hCwoAQOzJNcCvelLOU0wjPXq5L3cPOh/GyQ0MRHBf6viN4zbt2Q30IofU24filb/TS7fOEeReeLzTJdYbGvolkqz3zL0pU6sUqx2JmJ0mXXtXLAg7rSD53c7TYJHnE9mMhWlxquAop+fDiz4gy/7vDlY27XOLF50/0qguSIwplhMSk7Mq5Vo3DW64Y7jnfKAYC0312FnxxRkrk2ddcad1LMmBBUMx7mcRD69JvFJBlyq35TuC53PU336QFUO6vWS5D2y2+r5x+58vw7mkWzFSir01RnEn/8VeFpRshsj0ZKcB5lnilW5HyjnSjaIoeMersa9BK9Ixg4GtvmJhohFVSFStC/vS4Mo9XITBR6Yk49jwQNmOlTi5V/v58l1Rz3MgyXG2kUtmfvgbz5tsIHeBB5RyWSSAd538Xhymsqo2AqJr4cRT01dD7XjdtEuIuLq6Cx7FLN32ASPG0D2Pl0BMaiwdDOaTkkeZuzFEklw+haOqN38Ps42NDAk+Q9AOAiEuja0H5uIYkUyTam6xrlvJOI1XN1SXa8Lf6iN+C5G8ZwBacw+rQxe8+nfUU+KqFofGGMi/VKK+/mK/FbTKOo6tLqBVk3xGqfreBf1QpxyoyAz+ZjATc4Z+QKBtoXZqv6GdcY=
before_install:
- pip install pytest
script:
- docker build -t ${REPO} .
- pytest --testimage=${REPO}
after_success:
- bash deploy.sh
